import { Card, Carousel, Divider } from 'antd'
// import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Col, Container, Row } from 'react-bootstrap'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import { CalendarTwoTone, EditFilled, PhoneTwoTone, SearchOutlined, SendOutlined } from '@ant-design/icons';
import { Slide } from "react-awesome-reveal";
import { Button, Checkbox, Form, Input } from 'antd';
import ReactPlayer from 'react-player';
import SwipeableViews from 'react-swipeable-views';
import { autoPlay } from 'react-swipeable-views-utils';



const Home = () => {
  const router = useRouter();
  const AutoPlaySwipeableViews = autoPlay(SwipeableViews);
  const onFinish = (values) => {
    console.log('Success:', values);
  };

  const onFinishFailed = (errorInfo) => {
    console.log('Failed:', errorInfo);
  };
  return (
    <>
      <Carousel dots={false} effect='fade' autoplay>
        <div>
          <div className={styles.contentStyle}>
            <h2 style={{ fontSize: '3vw' }}><b>Leading the way in<br />medical excellence</b></h2>
            <p style={{ fontSize: '1vw' }}><b>Earth greater grass for good. Place for divide evening yielding<br />them that. Creeping beginning over gathered brought.</b></p>
            <Button type="primary" onClick={() => router.push("/services")}>Browse Services</Button>
          </div>
          <img width="100%" src="/assets/images/home-1.jpg"></img>
        </div>
        <div>
          <div className={styles.contentStyle}>
            <h2 style={{ fontSize: '3vw' }}><b>What are you<br />looking for?</b></h2>
            <p style={{ fontSize: '1vw' }}><b>I Like to Complete a Free Anxiety and Depression/Low Mood<br />Questionnaire to See How I am Feeling.</b></p>
            <Button type="primary" onClick={() => router.push("/services/free-self-assessment")}>Take Questionnaire</Button>
          </div>
          <img width="100%" src="/assets/images/home-2.png"></img>
        </div>
        <div>
          <div className={styles.contentStyle}>
            <h2 style={{ fontSize: '3vw' }}><b>About Us</b></h2>
            <p style={{ fontSize: '1vw' }}><b><strong>TwinBrain Ltd</strong>, owner of TwinBrain App, is a&nbsp;UK&nbsp;based healthcare in London<br />that operates on social enterprise principles. It was registered 30 April 2020<br />with Companies House  number 12580210.</b></p>
            <Button type="primary" onClick={() => router.push("/about-us")}>Find Out More</Button>
          </div>
          <img width="100%" src="/assets/images/home-3.png"></img>
        </div>
      </Carousel>
      <Container className="mb-5">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Row className='my-3'>
          <Col xs={12} sm={6} md={3}>
            <Slide triggerOnce direction='up' fraction={1}>
            <Card onClick={() => router.push("/")} className={styles.card} bordered={false} hoverable={true}>
              <CalendarTwoTone twoToneColor="#0dcaf0" style={{ fontSize: 40, color: "#0dcaf0" }} />
              <p>Book An Appointment</p>
            </Card>
            </Slide>
          </Col>
          <Col xs={12} sm={6} md={3}>
            <Slide triggerOnce direction='up' fraction={1} delay={200}>
            <Card onClick={() => router.push("/")} className={styles.card} bordered={false} hoverable={true}>
              <SendOutlined style={{ fontSize: 40, color: "#0dcaf0" }} />
              <p>Send A Message</p>
            </Card>
            </Slide>
          </Col>
          <Col xs={12} sm={6} md={3}>
            <Slide triggerOnce direction='up' fraction={1} delay={400}>
            <Card onClick={() => router.push("/")} className={styles.card} bordered={false} hoverable={true}>
              <PhoneTwoTone twoToneColor="#0dcaf0" style={{ fontSize: 40, color: "#0dcaf0" }} />
              <p>Call Our Team</p>
            </Card>
            </Slide>
          </Col>
          <Col xs={12} sm={6} md={3}>
            <Slide triggerOnce direction='up' fraction={1} delay={600}>
            <Card onClick={() => router.push("/")} className={styles.card} bordered={false} hoverable={true}>
              <SearchOutlined style={{ fontSize: 40, color: "#0dcaf0" }} />
              <p>Therapist Search</p>
            </Card>
            </Slide>
          </Col>
        </Row>

        <Row className='my-3' id={styles.row2}>
          <Col xs={12} sm={6}>
            <Slide triggerOnce direction='up' fraction={1}>
            <ReactPlayer
              url='/assets/video.mp4'
              width='100%'
              height='100%'
              controls={true}
            />
            </Slide>
          </Col>
          <Col xs={12} sm={6}>
            <Slide triggerOnce direction='up' fraction={1}>
            <h2 className='text-center'>Book An Appointment</h2>
            <Form
              name="basic"
              labelCol={{ span: 8 }}
              wrapperCol={{ span: 16 }}
              initialValues={{ remember: true }}
              onFinish={onFinish}
              onFinishFailed={onFinishFailed}
              autoComplete="off"
            >
              <Form.Item
                label="Name"
                name="name"
                rules={[{ required: true, message: 'Please input your name!' }]}
              >
                <Input />
              </Form.Item>

              <Form.Item
                label="Email"
                name="email"
                rules={[{ required: true, message: 'Please input your Email!' }]}
              >
                <Input />
              </Form.Item>
              <Form.Item
                label="Phone#"
                name="phone"
                rules={[{ required: true, message: 'Please input your Phone#!' }]}
              >
                <Input />
              </Form.Item>

              <Form.Item
                label="Location"
                name="location"
                rules={[{ required: true, message: 'Please input your Location!' }]}
              >
                <Input />
              </Form.Item>

              <Form.Item wrapperCol={{ offset: 8, span: 16 }}>
                <Button type="primary" htmlType="submit">
                  Book Now
                </Button>
              </Form.Item>
            </Form>
            </Slide>
          </Col>
        </Row>
        <Row>
          <h2 className='text-center'>Questionnaires</h2>
          <AutoPlaySwipeableViews>
            <div className={styles.questionnaire}>
              <Card>
                <div>
                  <EditFilled style={{ fontSize: 40 }} />
                </div>
                <div>
                  <h5>PHQ9 (Depression)</h5>
                  <Button type="primary" ghost={true}>
                    Click Here
                  </Button>
                </div>
              </Card>
              <Card>
                <div>
                  <EditFilled style={{ fontSize: 40 }} />
                </div>
                <div>
                  <h5>GAD7 (Anxiety)</h5>
                  <Button type="primary" ghost={true}>
                    Click Here
                  </Button>
                </div>
              </Card>
              <Card>
                <div>
                  <EditFilled style={{ fontSize: 40 }} />
                </div>
                <div>
                  <h5>IAPT Phobia Scale</h5>
                  <Button type="primary" ghost={true}>
                    Click Here
                  </Button>
                </div>
              </Card>
              <Card>
                <div>
                  <EditFilled style={{ fontSize: 40 }} />
                </div>
                <div>
                  <h5>Work and Social Adjustment Scale</h5>
                  <Button type="primary" ghost={true}>
                    Click Here
                  </Button>
                </div>
              </Card>
            </div>
            <div className={styles.questionnaire}>
              <Card>
                <div>
                  <EditFilled style={{ fontSize: 40 }} />
                </div>
                <div>
                  <h5>Empathy Quotient (EQ)</h5>
                  <Button type="primary" ghost={true}>
                    Click Here
                  </Button>
                </div>
              </Card>
              <Card>
                <div>
                  <EditFilled style={{ fontSize: 40 }} />
                </div>
                <div>
                  <h5>Autism Spectrum Quotient (AQ)</h5>
                  <Button type="primary" ghost={true}>
                    Click Here
                  </Button>
                </div>
              </Card>
              <Card>
                <div>
                  <EditFilled style={{ fontSize: 40 }} />
                </div>
                <div>
                  <h5>Complicated Grief Inventory</h5>
                  <Button type="primary" ghost={true}>
                    Click Here
                  </Button>
                </div>
              </Card>
              <Card>
                <div>
                  <EditFilled style={{ fontSize: 40 }} />
                </div>
                <div>
                  <h5>Child and Adolescent Disruptive Behaviour Inventory - Parent Survey (CADBI)</h5>
                  <Button type="primary" ghost={true}>
                    Click Here
                  </Button>
                </div>
              </Card>
            </div>
          </AutoPlaySwipeableViews>
        </Row>
      </Container>
    </>
  )
}

export default Home
