import { Carousel } from 'antd'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Button } from 'react-bootstrap'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <>
      <Carousel effect='fade' autoplay>
        <div>
          <div className={styles.contentStyle}>
            <h2 style={{ fontSize: '3vw' }}><b>Leading the way in<br />medical excellence</b></h2>
            <p style={{ fontSize: '1vw' }}><b>Earth greater grass for good. Place for divide evening yielding<br />them that. Creeping beginning over gathered brought.</b></p>
            <Button style={{color: 'white'}} onClick={() => router.push("/services")}>Browse Services</Button>
          </div>
          <img width="100%" src="/assets/images/home-1.jpg"></img>
        </div>
        <div>
          <div className={styles.contentStyle}>
            <h2 style={{ fontSize: '3vw' }}><b>What are you<br />looking for?</b></h2>
            <p style={{ fontSize: '1vw' }}><b>I Like to Complete a Free Anxiety and Depression/Low Mood<br />Questionnaire to See How I am Feeling.</b></p>
            <Button onClick={() => router.push("/services/free-self-assessment")}>Take Questionnaire</Button>
          </div>
          <img width="100%" src="/assets/images/home-2.png"></img>
        </div>
        <div>
        <div className={styles.contentStyle}>
            <h2 style={{ fontSize: '3vw' }}><b>About Us</b></h2>
            <p style={{ fontSize: '1vw' }}><b><strong>TwinBrain Ltd</strong>, owner of TwinBrain App, is a&nbsp;UK&nbsp;based healthcare in London<br/>that operates on social enterprise principles. It was registered 30 April 2020<br/>with Companies House  number 12580210.</b></p>
            <Button onClick={() => router.push("/about-us")}>Find Out More</Button>
          </div>
          <img width="100%" src="/assets/images/home-3.png"></img>
        </div>
      </Carousel>
      <h1 style={{ margin: 200, textAlign: 'center' }}>Further content will come here</h1>
    </>
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </h1>

    //     <p className={styles.description}>
    //       Get started by editing{' '}
    //       <code className={styles.code}>pages/index.tsx</code>
    //     </p>

    //     <div className={styles.grid}>
    //       <a href="https://nextjs.org/docs" className={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>

    //       <a href="https://nextjs.org/learn" className={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>

    //       <a
    //         href="https://github.com/vercel/next.js/tree/canary/examples"
    //         className={styles.card}
    //       >
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //       >
    //         <h2>Deploy &rarr;</h2>
    //         <p>
    //           Instantly deploy your Next.js site to a public URL with Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{' '}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
  )
}

export default Home
